name: promote
on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch: {}

jobs:
  release:
    name: promote
    runs-on: ubuntu-latest
    environment: promote
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        id: checkout
        env:
          has_promote_token: ${{ secrets.PROMOTE_TOKEN && '1' || '' }}
        if: env.has_promote_token
        with:
          fetch-depth: 0
          ref: master
          token: ${{ secrets.PROMOTE_TOKEN }}
      - uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2
        if: steps.checkout.conclusion != 'skipped'
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        if: steps.checkout.conclusion != 'skipped'
        with:
          go-version-file: go.mod
      - run: make promote
        if: steps.checkout.conclusion != 'skipped'
